MovieCatalog/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieCatalog.Dao;
using MovieCatalog.Helpers;
using MovieCatalog.Models;
using MovieCatalog.ViewModels;
using System;
using System.Linq;

namespace MovieCatalog.Controllers
{
    public class CatalogController : BaseController
    {

        public const string ControllerName = "catalog";
        protected override string GetControllerName() => ControllerName;

        public CatalogController(
            ILogger<CatalogController> logger,
            MovieCatalogContext context,
            IWebHostEnvironment hostEnvironment
        ) : base(logger, context, hostEnvironment)
        {}

        public const string MainPageActionName = "movies";
        [ActionName(MainPageActionName), HttpGet]
        public IActionResult Movies(int? page)
        {
            var vm = new MoviesViewModel();
            var movieDaoManager = new MovieDaoManager(_context);
            vm.Movies = movieDaoManager.GetPage(page-1).AsEnumerable();
            vm.Pages = movieDaoManager.GetAll().Count() / 10;
            return View("~/Views/Movies/Index.cshtml", vm);
        }

        public const string MoviePageActionName = "movie";
        [ActionName(MoviePageActionName), HttpGet]
        public IActionResult MoviePage(int? id)
        {
            var vm = new MoviePageViewModel();
            var movieDaoManager = new MovieDaoManager(_context);
            Movie movie = movieDaoManager.GetMovieById(id.Value);
            if (movie == null)
                return ControllerRedirect("movies");

            vm.Movie = movie;
            return View("~/Views/Movies/Movie.cshtml", vm);
        }

        public const string AddMoviePageActionName = "add";
        [ActionName(AddMoviePageActionName), HttpGet]
        public IActionResult AddMoviePage()
        {
            var vm = new MovieFormViewModel();
            
            vm.Covers = FileHelper.GetFiles(_hostEnvironment.WebRootPath);
            vm.FormPostUrl = AddMovieActionName;
            FindSuccessAndErrorMessages(vm);

            return View("~/Views/Movies/Form.cshtml", vm);
        }

        public const string AddMovieActionName = "add";
        [ActionName(AddMovieActionName), HttpPost]
        public IActionResult AddMovie(Movie movie)
        {
            var movieDaoManager = new MovieDaoManager(_context);
            Exception error = movieDaoManager.AddMovie(movie, ViewerHelper.GetCurrent(HttpContext));

            if (error != null)
                ErrorHelper.SetFormError(HttpContext, error);
            else
                FormMessageHelper.SetSuccessMessage(HttpContext, "Фильм добавлен успешно!");

            return ControllerRedirect("add");
        }

        public const string EditMoviePageActionName = "edit";
        [ActionName(EditMoviePageActionName), HttpGet]
        public IActionResult EditMoviePage(int? id)
        {
            if (id == null)
                return ControllerRedirect("/");

            var movieDaoManager = new MovieDaoManager(_context);
            var vm = new MovieFormViewModel();

            vm.Covers = FileHelper.GetFiles(_hostEnvironment.WebRootPath);
            vm.Movie = movieDaoManager.GetById(id.Value);
            vm.FormPostUrl = EditMovieActionName;
            FindSuccessAndErrorMessages(vm);

            return View("~/Views/Movies/Form.cshtml", vm);
        }

        public const string EditMovieActionName = "edit";
        [ActionName(EditMovieActionName), HttpPost]
        public IActionResult EditMovie(Movie movie)
        {
            var movieDaoManager = new MovieDaoManager(_context);
            Exception error = movieDaoManager.UpdateMovie(movie);
            if (error != null)
                ErrorHelper.SetFormError(HttpContext, error);
            else
                FormMessageHelper.SetSuccessMessage(HttpContext, "Изменения сохранены успешно");
            return ControllerRedirect($"edit?id={movie.Id}");
        }

        public const string DeleteMovieActionName = "delete";
        [ActionName(DeleteMovieActionName)]
        public IActionResult DeleteMovie(int? id)
        {
            if (id != null)
            {
                var movieDaoManager = new MovieDaoManager(_context);
                movieDaoManager.Delete(id.Value);
            }

            return ControllerRedirect("movies");
        }

        private void FindSuccessAndErrorMessages(MovieFormViewModel vm)
        {
            string errorMessage = ErrorHelper.GetFormError(HttpContext);
            if (errorMessage != null)
            {
                vm.ErrorMessage = errorMessage;
                ErrorHelper.RemoveFormError(HttpContext);
                return;
            }

            string successMessage = FormMessageHelper.GetSuccessMessage(HttpContext);
            if (successMessage != null)
            {
                vm.SuccessMessage = successMessage;
                FormMessageHelper.RemoveSuccessMessage(HttpContext);
            }
        }

    }
}

MovieCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieCatalog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/movies.css" />
    <link rel="stylesheet" href="~/css/files.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Catalog" asp-action="Movies">MovieCatalog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (ViewBag.Viewer != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="catalog" asp-action="add">Добавить фильм</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="file" asp-action="upload">Изображения</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="auth" asp-action="logout">Выйти</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="auth" asp-action="login">Авторизация</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-controller="auth" asp-action="register">Регистрация</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="jumbotron">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MovieCatalog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/PickCover.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>